---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todo-app
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  strategy: {}
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
      - image: gustavolscheffer/flask_app:latest
        name: flask-app-v5qh8
        ports:
        - containerPort: 5000
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-app
  name: todo-app
spec:
  ports:
  - name: 5000-tcp
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: todo-app
  type: NodePort
status:
  loadBalancer: {}
